name: Python Workflow
on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Tests
      run: python tests.py
